# /media:
  # /utterances:
    type: 
      media.result:
        item.name: utterances
        item.human.name: set of utterances
        get.collection.example: !include media.utterances.get.json
        get.item.example: !include media.utterances.item.get.json